apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: p5nka3b44-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/p5nka3b44-dotnet-basic-gitops